version: '3'

services:
  postgres:
    image: postgres:16
    container_name: pg-test-hex
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - ./src/common/infraestructure/database/postgresql:/var/lib/postgresql/data

  mongo:
    image: mongo:latest
    container_name: mongo-test-hex
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DB_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - ./src/common/infraestructure/database/mongodata:/data/db

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PG_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PG_PASSWORD}
    ports:
      - '5050:80'
    volumes:
      - ./src/common/infraestructure/database/pgadmin:/var/lib/pgadmin

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_EXPRESS_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_EXPRESS_PASSWORD}
      - ME_CONFIG_MONGODB_URL=${MONGO_EXPRESS_URL}
      - ME_CONFIG_BASICAUTH=false