version: '3'

services:
  postgres:
    image: postgres:16
    container_name: test-hex
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - ./src/common/infraestructure/database/postgresql:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pg-test-hex
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PG_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PG_PASSWORD}
    ports:
      - '5050:80'
    volumes:
      - ./src/common/infraestructure/database/pgadmin:/var/lib/pgadmin